### ISSUE TITLE
Upload fact files

### ISSUE THREAD

**Issue by raphink** [Sharpie/puppet-facts_upload#5]
Would it be possible to use this to upload facts files (YAML, JSON) instead of calling facter?

The need would be syncing facts files from an external Puppet Master (in DMZ) and uploading them to the PuppetDB afterwards.

**Comment by Sharpie** [comment]
This module was way to re-implement the `puppet facts upload` command prior to it's official re-introduction in Puppet 5.5.0:

https://tickets.puppetlabs.com/browse/PUP-7779

The code contained here was essentially copied right back into the main Puppet source tree. Beyond its use as a prototype, this module does allow the `puppet facts upload` functionality to be "backported" to Puppet 4.10 -- 5.4.

So, anything you can do with `puppet facts upload` can be done with this module, but using the latest Puppet 5 or Puppet 6 releases would be preferable as the functionality is built-in.

Any new functionality should be implemented as a new module as this one is deep in maintenance mode and will be archived when Puppet 5 passes End of Life.
